version: "3.7"
services:
  frontend:
    build: ./frontend
    image: sync_frontend
    container_name: sync_frontend
    ports:
      - 8080:80
    depends_on:
      - backend
  backend:
    build: ./backend
    image: sync_backend
    container_name: sync_backend
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis
    container_name: sync_redis
